In [19]:
import numpy as np

### random module
rand - random values in given shape<br>
randn- return a sample (or samples) from the standard normal distribution<br>
randint - return random values from low(inclusive) to high(exclusive)<br>
random - return random floats in the half open interval<br>
choice - generate a random choice from a given 1D array<br>
shuffle - shuffles the content of sequence<br>

In [20]:
ar = np.random.rand(2, 3)

In [21]:
ar

array([[0.0843433 , 0.77816219, 0.00695855],
       [0.90011583, 0.28813909, 0.04216235]])

In [30]:
arr  = np.arange(10) + 5

In [31]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
np.random.shuffle(arr)

In [33]:
arr

array([ 8, 10,  7,  6, 13,  5, 11, 14, 12,  9])