In [0]:
import torch
import torch.nn as nn

In [0]:
X = torch.tensor(([2, 9], [1, 5], [3, 6]), dtype=torch.float) # 3 X 2 tensor
y = torch.tensor(([92], [100], [89]), dtype=torch.float) # 3 X 1 tensor
xPredicted = torch.tensor(([4, 8]), dtype=torch.float) # 1 X 2 tensor

In [7]:
print(X.size())

torch.Size([3, 2])


### scaling what is also called normalization

In [0]:
# scale units
X_max, _ = torch.max(X, 0)
xPredicted_max, _ = torch.max(xPredicted, 0)

In [0]:
X = torch.div(X, X_max)
xPredicted = torch.div(xPredicted, xPredicted_max)
y = y / 100  # max test score is 100

In [11]:
X

tensor([[0.6667, 1.0000],
        [0.3333, 0.5556],
        [1.0000, 0.6667]])

### model

In [0]:
class Neural_Network(nn.Module):
    def __init__(self, ):
        super(Neural_Network, self).__init__()
        # parameters
        # TODO: parameters can be parameterized instead of declaring them here
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        # weights
        self.W1 = torch.randn(self.inputSize, self.hiddenSize) # 3 X 2 tensor
        self.W2 = torch.randn(self.hiddenSize, self.outputSize) # 3 X 1 tensor
        
    def forward(self, X):
        self.z = torch.matmul(X, self.W1) # 3 X 3 ".dot" does not broadcast in PyTorch
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = torch.matmul(self.z2, self.W2)
        o = self.sigmoid(self.z3) # final activation function
        return o
        
    def sigmoid(self, s):
        return 1 / (1 + torch.exp(-s))
    
    def sigmoidPrime(self, s):
        # derivative of sigmoid
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # derivative of sig to error
        self.z2_error = torch.matmul(self.o_delta, torch.t(self.W2))
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)
        self.W1 += torch.matmul(torch.t(X), self.z2_delta)
        self.W2 += torch.matmul(torch.t(self.z2), self.o_delta)
        
    def train(self, X, y):
        # forward + backward pass for training
        o = self.forward(X)
        self.backward(X, y, o)
        
    def saveWeights(self, model):
        # we will use the PyTorch internal storage functions
        torch.save(model, "NN")
        # you can reload model with all the weights and so forth with:
        # torch.load("NN")
        
    def predict(self):
        print ("Predicted data based on trained weights: ")
        print ("Input (scaled): \n" + str(xPredicted))
        print ("Output: \n" + str(self.forward(xPredicted)))

In [0]:
NN = Neural_Network()

In [16]:
NN = Neural_Network()
for i in range(100):  # trains the NN 1,000 times
    print ("#" + str(i) + " Loss: " + str(torch.mean((y - NN(X))**2).detach().item()))  # mean sum squared loss
    NN.train(X, y)

#0 Loss: 0.35289517045021057
#1 Loss: 0.2923568785190582
#2 Loss: 0.24119548499584198
#3 Loss: 0.1988474279642105
#4 Loss: 0.16405947506427765
#5 Loss: 0.13558875024318695
#6 Loss: 0.11237818002700806
#7 Loss: 0.09353840351104736
#8 Loss: 0.07830509543418884
#9 Loss: 0.06601537019014359
#10 Loss: 0.05610107257962227
#11 Loss: 0.04808572307229042
#12 Loss: 0.04157908260822296
#13 Loss: 0.03626786544919014
#14 Loss: 0.03190403804183006
#15 Loss: 0.028293101117014885
#16 Loss: 0.0252830907702446
#17 Loss: 0.022755473852157593
#18 Loss: 0.020617499947547913
#19 Loss: 0.01879645697772503
#20 Loss: 0.01723496802151203
#21 Loss: 0.015887530520558357
#22 Loss: 0.01471784058958292
#23 Loss: 0.013696718029677868
#24 Loss: 0.01280056033283472
#25 Loss: 0.012010167352855206
#26 Loss: 0.011309816502034664
#27 Loss: 0.010686547495424747
#28 Loss: 0.010129586793482304
#29 Loss: 0.009629976935684681
#30 Loss: 0.009180202148854733
#31 Loss: 0.008773901499807835
#32 Loss: 0.0084057142958045
#33 Loss: 0.

In [17]:
NN.saveWeights(NN)
NN.predict()

Predicted data based on trained weights: 
Input (scaled): 
tensor([0.5000, 1.0000])
Output: 
tensor([0.9169])


/usr/local/lib/python3.6/dist-packages/torch/serialization.py:256: UserWarning: Couldn't retrieve source code for container of type Neural_Network. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
