#### What is PyTorch?
It’s a Python-based scientific computing package targeted at two sets of audiences:
- A replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed


In [1]:
import torch

In [7]:
import numpy as np

In [16]:
ones = torch.rand(5, 5) # empty array

In [17]:
ones

tensor([[0.1787, 0.0405, 0.8261, 0.7377, 0.4453],
        [0.4982, 0.7092, 0.5729, 0.1068, 0.9367],
        [0.4963, 0.2166, 0.6282, 0.1858, 0.0249],
        [0.7944, 0.6917, 0.2877, 0.9070, 0.7998],
        [0.3157, 0.5613, 0.6805, 0.8957, 0.2998]])

In [15]:
torch.unique(ones)

tensor([1.])

Construct a tensor directly from data:

In [20]:
x = torch.tensor([3, 4.0])

In [21]:
print(x)

tensor([3., 4.])


-  create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [22]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5903,  0.4167, -0.5953],
        [-0.7799, -0.0868, -0.1189],
        [ 0.8814,  0.4308,  0.7736],
        [ 0.3191, -0.5066,  1.3645],
        [-0.3490, -1.0647, -1.2521]])


-  ### Converting a Torch Tensor to a NumPy Array

In [25]:
a = torch.ones(4)

In [27]:
print(a, type(a))

tensor([1., 1., 1., 1.]) <class 'torch.Tensor'>


In [28]:
b = a.numpy()

In [29]:
print(b, type(b))

[1. 1. 1. 1.] <class 'numpy.ndarray'>


- See how the numpy array changed in value.

In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]
