### closed form solution of linear regression

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets as ds

In [6]:
## Generating dataset using sklearn datatset function
ds.make_regression?

In [7]:
X, Y = ds.make_regression(n_samples= 400, n_features= 5, n_informative=3, noise= 0.5, random_state= 10)

In [12]:
print(X.shape)
print(Y.shape)

(400, 5)
(400,)


In [13]:
# we have to reshape Y
Y = np.reshape(Y, (-1, 1))

In [14]:
print(Y.shape)

(400, 1)


In [24]:
print(Y[:5])

[[  28.65030275]
 [-160.63611766]
 [  32.27455993]
 [  12.00559464]
 [  57.92302826]]


In [16]:
# we have to add an extra colomn into the X
ones = np.ones((X.shape[0], 1))

X = np.hstack((ones, X))

In [17]:
print(X[:4])

[[ 1.         -0.67202344  1.34217928 -0.37276142 -0.40147282  0.40246909]
 [ 1.         -0.4557819   0.39932737 -0.52660803 -0.3854609  -2.5114691 ]
 [ 1.          0.2519878  -1.2151136   0.24542898  0.68340726  0.53156124]
 [ 1.         -1.15646365 -0.29308894  1.1180308  -0.12986709  0.21352913]]


### closed form method formula
- theta = inv(trX.X).(trX.Y)
- tra - transpose
- inv - inverse

In [18]:
def getTheta(x, y):
    xt = x.T
    first_term = np.linalg.pinv(np.dot(xt, x))
    second_term = np.dot(xt, y)
    return np.dot(first_term, second_term)

In [19]:
theta = getTheta(X, Y)

In [22]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

## Its time to make predictions

In [43]:
test = X[16]
test = np.reshape(test, (-1, 1))

In [44]:
print(test.shape)

(6, 1)


In [45]:
trTheta = theta.T

In [46]:
pred = np.dot(trTheta, test)

In [47]:
pred

array([[-50.96009677]])

In [48]:
Y[16]

array([-50.28953251])

## cool prediction has been made