In [29]:
x = ['This was awesome movie',
    'Great movie! I liked it a lot',
    'Happy Ending! awesome acting by the hero',
    'loved it! truly great',
    'bad not upto the mark',
    'could have been better',
    'surely a disappointing movie']
y = [1, 1,  1, 1, 0, 0, 0]
# 1 postive
# 0 negative

In [30]:
x_test = ['I was happy & happy and I loved the acting in the movie',
         'The movie I saw was bad',
         'I was disappointed with it']


In [31]:
sample_text = """I loved this movie since I was 7 and I saw it on the opening day. It was so touching and beautiful. I strongly recommend seeing for all. It's a movie to watch with your family by far.<br /><br />My MPAA rating: PG-13 for thematic elements, prolonged scenes of disastor, nudity/sexuality and some language.
First things first, Edison Chen did a fantastic, believable job as a Cambodian hit-man, born and bred in the dumps and a gladiatorial ring, where he honed his craft of savage battery in order to survive, living on the mantra of kill or be killed. In a role that had little dialogue, or at least a few lines in Cambodian/Thai, his performance is compelling, probably what should have been in the Jet Li vehicle Danny the Dog, where a man is bred for the sole purpose of fighting, and on someone else's leash.<br /><br />Like Danny the Dog, the much talked about bare knuckle fight sequences are not choreographed stylistically, but rather designed as normal, brutal fisticuffs, where everything goes. This probably brought a sense of realism and grit when you see the characters slug it out at each other's throats, in defending their own lives while taking it away from others. It's a grim, gritty and dark movie both literally and figuratively, and this sets it apart from the usual run off the mill cop thriller production.<br /><br />"""

In [6]:
print(sample_text)

I loved this movie since I was 7 and I saw it on the opening day. It was so touching and beautiful. I strongly recommend seeing for all. It's a movie to watch with your family by far.<br /><br />My MPAA rating: PG-13 for thematic elements, prolonged scenes of disastor, nudity/sexuality and some language.
First things first, Edison Chen did a fantastic, believable job as a Cambodian hit-man, born and bred in the dumps and a gladiatorial ring, where he honed his craft of savage battery in order to survive, living on the mantra of kill or be killed. In a role that had little dialogue, or at least a few lines in Cambodian/Thai, his performance is compelling, probably what should have been in the Jet Li vehicle Danny the Dog, where a man is bred for the sole purpose of fighting, and on someone else's leash.<br /><br />Like Danny the Dog, the much talked about bare knuckle fight sequences are not choreographed stylistically, but rather designed as normal, brutal fisticuffs, where everything 

In [7]:
from nltk.tokenize  import RegexpTokenizer
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [8]:
clean_text = sample_text.replace("<br /><br />", "")

In [9]:
print(clean_text)

I loved this movie since I was 7 and I saw it on the opening day. It was so touching and beautiful. I strongly recommend seeing for all. It's a movie to watch with your family by far.My MPAA rating: PG-13 for thematic elements, prolonged scenes of disastor, nudity/sexuality and some language.
First things first, Edison Chen did a fantastic, believable job as a Cambodian hit-man, born and bred in the dumps and a gladiatorial ring, where he honed his craft of savage battery in order to survive, living on the mantra of kill or be killed. In a role that had little dialogue, or at least a few lines in Cambodian/Thai, his performance is compelling, probably what should have been in the Jet Li vehicle Danny the Dog, where a man is bred for the sole purpose of fighting, and on someone else's leash.Like Danny the Dog, the much talked about bare knuckle fight sequences are not choreographed stylistically, but rather designed as normal, brutal fisticuffs, where everything goes. This probably brou

In [33]:
ps = PorterStemmer()
tokenizer = RegexpTokenizer('[a-zA-Z]+')
stopword = set(stopwords.words('english'))

In [34]:
def clean_view(review):
    review = review.lower()
    review = review.replace("<br /><br />", "")
    tokens = tokenizer.tokenize(review)
    new_token = [ps.stem(token) for token in tokens if token not in stopword]
    
    return ' '.join(new_token)
    

In [95]:
x_train = [clean_view(sent) for sent in x]
x_test = [clean_view(sent) for sent in x_test]

In [96]:
print(x_train)

['awesom movi', 'great movi like lot', 'happi end awesom act hero', 'love truli great', 'bad upto mark', 'could better', 'sure disappoint movi']


In [102]:
from sklearn.feature_extraction.text import CountVectorizer

In [103]:
cv = CountVectorizer(ngram_range=(1, 1))

In [104]:
cv.fit(x_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [105]:
x_train_vect = cv.transform(x_train).toarray()
x_test_vect = cv.transform(x_test).toarray()

In [106]:
print(x_test_vect)

[[1 0 0 0 0 0 0 0 2 0 0 0 1 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]


In [107]:
cv.vocabulary_

{'awesom': 1,
 'movi': 14,
 'great': 7,
 'like': 10,
 'lot': 11,
 'happi': 8,
 'end': 6,
 'act': 0,
 'hero': 9,
 'love': 12,
 'truli': 16,
 'bad': 2,
 'upto': 17,
 'mark': 13,
 'could': 4,
 'better': 3,
 'sure': 15,
 'disappoint': 5}

In [108]:
from sklearn.naive_bayes import MultinomialNB

In [109]:
model = MultinomialNB()
model.fit(x_train_vect, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [110]:
model.predict(x_test_vect)

array([1, 0, 0])